baseURL = "https://shadab-bigdel.github.io/"
languageCode = "en-us"
title = "Shadab Bigdel — Senior AWS Cloud Architect"
theme = "hugo-coder"

# Optional: main menu for navigation
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 2

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

